export const UPDATE_REGISTER_INFO = 'UPDATE_REGISTER_INFO';
export const UPDATE_PROFILE_NAME = 'UPDATE_PROFILE_NAME';
export const UPDATE_LOGIN_INFO = 'UPDATE_LOGIN_INFO';
export const UPDATE_SHOW_MODAL_WINDOW = "UPDATE_SHOW_MODAL_WINDOW";